version: '3'

services:
  db:
    image: postgres:15.4-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POStGRES_DB=myapp_prod

  web:
    build:
      context: .
      secrets:
        - master_key
    ports:
      - 8080:8080
    env_file:
      - production.env
    depends_on:
      - db

secrets:
  master_key:
    file: config/master.key

volumes:
  postgresql_data:
