version: '3'

services:
  db:
    image: postgres:15.4-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POStGRES_DB=myapp_dev

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
    environment:
      BUNDLE_PATH: "/app/vendor/bundle"
      BINDING: "0.0.0.0"
      MYAPP_DATABASE_USERNAME: postgres
      MYAPP_DATABASE_PASSWORD: password
      MYAPP_DATABASE_HOST: db
    command: ["bin/dev"]
    expose: ["3000"]
    ports: ["3000:3000"]
    working_dir: /app
    depends_on:
      - db

volumes:
  bundle:
  node_modules:
  postgresql_data:
