default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: myapp_dev
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['MYAPP_DATABASE_HOST'] %>

test:
  <<: *default
  database: myapp_test
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['MYAPP_DATABASE_HOST'] %>

production:
  <<: *default
  database: myapp_prod
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['MYAPP_DATABASE_HOST'] %>
